name: Deploy Node.js app to Azure Web App - serverDemoApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'serverDemoApp'
          slot-name: 'Production'
          package: backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2FDE934EBCEC4F1E9F9949A17AAF2ECA }}


